export const ActionTypes = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  LOGIN_SUCCESS_BY_GOOGLE: "LOGIN_SUCCESS_BY_GOOGLE",
  LOGIN_FAILURE_BY_GOOGLE: "LOGIN_FAILURE_BY_GOOGLE",
  SIGNOUT_SUCCESS_BY_GOOGLE: "SIGNOUT_SUCCESS_BY_GOOGLE",
  TEMP_LOGIN_SUCCESS: "TEMP_LOGIN_SUCCESS",
  TEMP_LOGIN_FAILURE: "TEMP_LOGIN_FAILURE",
  DUMMY_LOGIN_SUCCESS: "DUMMY_LOGIN_SUCCESS",
};
