const data = [
  {},
  {
    name: "Zomato",
    operationHealth: [
      {
        name: "Rest. Serviceability",
        value: 80,
        type: "percentage",
        info: "Servicibility > 95% Gets more orders",
        monthlyResult: 85,
        weeklyResult: 90,

        // not using right now
        "Daily Servicibility": 100,
        Date: "2021-12-13",
        "Email ID": "npmbaskar@gmail.com",
        Month: 12,
        Monthly_Servicibility: 86,
        Nomenclature: "Chettinad food house",
        "Time lag": 1,
        Week_Tagger: "Last 7 days",
        Weekly_Servicibility: 98,
        res_id: 256302,
        _id: "61b84b426ee9e5d3665e150f",
      },
      {
        name: "Cancellation Charges",
        value: 60,
        type: "percentage",
        info: "Cancellation Charges > 95% Gets better orders",
        monthlyResult: 0.03,
        weeklyResult: 0.05,

        Date: "2021-12-13",
        "Email ID": "npmbaskar@gmail.com",
        Month: 12,
        Monthly_avg_RDC: 0.01,
        Nomenclature: "Chettinad food house",
        RDC: 0,
        "Res Id": 256302,
        Res_Cancellation: 0,
        "Time lag": 1,
        "Total Orders": 28,
        Total_Cancellation: 1,
        Week_Tagger: "Last 7 days",
        Weekly_avg_RDC: 0,
        _id: "61b84df094cc169f4a4c86f8",
      },
      // always in minutes
      {
        name: "Preparation Time",
        value: 56,
        type: "time",
        info: "Time > 15mins Get more orders",
        monthlyResult: 15,
        weeklyResult: 12,
      },
      {
        name: "Average Rating",
        value: 4.5,
        type: "rating",
        info: "Rating > 4 Gets better orders",
        monthlyResult: 4.1,
        weeklyResult: 4.6,

        Customer_Ratings: 3.9,
        Date: "2021-12-14",
        "Email ID": "npmbaskar@gmail.com",
        Month: 12,
        Monthly_Rating: 3.96,
        Nomenclature: "Chettinad food house",
        "Res ID": 256302,
        "Time lag": 0,
        Week_Tagger: "",
        Weekly_Rating: 4.1,
      },
      {
        name: "MFR Accuracy",
        value: 85,
        type: "percentage",
        info: "Calculated for according to the data",
        monthlyResult: 89,
        weeklyResult: 92,

        Date: "2021-12-13",
        "Email ID": "npmbaskar@gmail.com",
        Good_food_ready_Count: 27,
        Mfr: 96,
        Month: 12,
        Monthly_Mfr: 87,
        Nomenclature: "Chettinad food house",
        Res_Id: 256302,
        "Time lag": 1,
        Week_Tagger: "Last 7 days",
        Weekly_Mfr: 89,
        total_orders: 28,
        _id: "61b84d1b7ab010f4d6312684",
      },
    ],
    listingScore:[
      {
        name: "Rest. Serviceability",
        value: 80,
        type: "percentage",
        info: "Servicibility > 95% Gets more orders",
        monthlyResult: 85,
        weeklyResult: 90,

        // not using right now
        "Daily Servicibility": 100,
        Date: "2021-12-13",
        "Email ID": "npmbaskar@gmail.com",
        Month: 12,
        Monthly_Servicibility: 86,
        Nomenclature: "Chettinad food house",
        "Time lag": 1,
        Week_Tagger: "Last 7 days",
        Weekly_Servicibility: 98,
        res_id: 256302,
        _id: "61b84b426ee9e5d3665e150f",
      },
      {
        name: "Cancellation Charges",
        value: 60,
        type: "percentage",
        info: "Cancellation Charges > 95% Gets better orders",
        monthlyResult: 0.03,
        weeklyResult: 0.05,

        Date: "2021-12-13",
        "Email ID": "npmbaskar@gmail.com",
        Month: 12,
        Monthly_avg_RDC: 0.01,
        Nomenclature: "Chettinad food house",
        RDC: 0,
        "Res Id": 256302,
        Res_Cancellation: 0,
        "Time lag": 1,
        "Total Orders": 28,
        Total_Cancellation: 1,
        Week_Tagger: "Last 7 days",
        Weekly_avg_RDC: 0,
        _id: "61b84df094cc169f4a4c86f8",
      },
      // always in minutes
      {
        name: "Preparation Time",
        value: 56,
        type: "time",
        info: "Time > 15mins Get more orders",
        monthlyResult: 15,
        weeklyResult: 12,
      },
      {
        name: "Average Rating",
        value: 4.5,
        type: "rating",
        info: "Rating > 4 Gets better orders",
        monthlyResult: 4.1,
        weeklyResult: 4.6,

        Customer_Ratings: 3.9,
        Date: "2021-12-14",
        "Email ID": "npmbaskar@gmail.com",
        Month: 12,
        Monthly_Rating: 3.96,
        Nomenclature: "Chettinad food house",
        "Res ID": 256302,
        "Time lag": 0,
        Week_Tagger: "",
        Weekly_Rating: 4.1,
      },
      {
        name: "MFR Accuracy",
        value: 85,
        type: "percentage",
        info: "Calculated for according to the data",
        monthlyResult: 89,
        weeklyResult: 92,

        Date: "2021-12-13",
        "Email ID": "npmbaskar@gmail.com",
        Good_food_ready_Count: 27,
        Mfr: 96,
        Month: 12,
        Monthly_Mfr: 87,
        Nomenclature: "Chettinad food house",
        Res_Id: 256302,
        "Time lag": 1,
        Week_Tagger: "Last 7 days",
        Weekly_Mfr: 89,
        total_orders: 28,
        _id: "61b84d1b7ab010f4d6312684",
      },
    ],
    adsAndAnalytics: {
      costPerClick: 700,
      sales: 12000,
      returnOnInvestment: 3,
      possibleReturns: 6,
      suggestions: ["Remove Banner Ads", "Increase CPC $7000"],
      revenue: {
        Daily_Discount_amount: 0,
        Daily_Sub_Total: 3945,
        Daily_Total_Revenue: 4302,
        Daily_Total_Tax: 0,
        Daily_Total_before_Tax: 4302,
        Daily_package_charge: 357,
        Date: "2021-12-13",
        "Final Revenue": 3036.35,
        Monthly_Revenue: 35630.29,
        Nomenclature: "Chettinad food house",
        Res_Id: 256302,
        Swiggy_Service_Tax: 185.85,
        Swiggy_TCS: 47.32,
        Swiggy_TDS: 0,
        Swiggy_commision: 1032.48,
        "Time lag": 1,
        Week_Tagger: "Last 7 days",
        Weekly_Revenue: 3036.35,
        _id: "61b84d99710940015bc1fb6c",
      },
    },
    customerReviews: {
      positive: [
        {
          id: 1,
          date: "20201107",
          rating: 5,
          review:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore",
        },
      ],
      negative: [
        {
          id: 11,
          name: "Dal Makhni",
          issues: [
            { name: "oil", percentage: 70 },
            { name: "spice", percentage: 10 },
            { name: "issue 3", percentage: 52 },
          ],
        },
        {
          id: 12,
          name: "Masala Dosa",
          issues: [
            { name: "oil", percentage: 60 },
            { name: "spice", percentage: 40 },
            { name: "issue 3", percentage: 40 },
          ],
        },
      ],
      OrdersPerRating: {
        "5_star": 5,
        "4_star": 1,
        "3_star": 7,
        "2_star": 3,
        "1_star": 4,
      },
      monthlyResult: 3.9,
      weeklyResult: 4.1,
      totalRatings: 20,
    },
  },
];

module.exports = data;
